#!/bin/sh
echo "****************************************"
echo "*             tvManager installed      *"
echo "*                                      *"
echo "*       Enjoy our plugin               *"
echo "****************************************"
echo "*   Please .. Restarting Enigma2       *"
echo "*     all right reserved               *"
echo "*          no copy                     *"
echo "****************************************"

cmd22='/usr/bin/wget'
cmd23=$(apt-get update && apt-get install wget)
if [ -f $cmd22 ]; then
    echo "wget exist"
else apt-get update && apt-get install wget
fi

wget -q --no-check-certificate https://raw.githubusercontent.com/Belfagor2005/tvManager/main/installer.sh -O - | /bin/sh

exit 0
