#!/bin/sh
# if [ -d /usr/lib/python2.6 ]; then
# if [ ! -d /usr/lib/python2.7 ]; then
# echo "**********************************************************"
# echo "*                        Oooooooops                      *"
# echo "*                Not Compatible with (OE1.6)             *"
# echo "**********************************************************"
# sleep 2
# fi
# fi
# exit 1 
echo "Checking for an older version in the system..."
if [ -d /usr/lib/enigma2/python/Plugins/Extensions/tvManager ]
then 
echo "tvManager Installato"
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/tvManager > /dev/null 2>&1
echo "Una versione precedente trovata e rimossa..."
else
echo "Nessun Plugin tvManager Installato"
echo "***********************************"
echo "* Proceeding to installation...   *"
echo "***********************************"
fi
